"""Public interface of the Shed engine.

The engine owns cards, authoritative state, observations, legality, and
transitions. It depends only on the standard library and never imports agents,
timing, scripts, or multiprocessing.

Milestone status: the deck, deterministic dealing, state and player views, the
event vocabulary, legal-move generation, and the SETUP transition are
implemented. Ordinary PLAY resolution is the remaining engine work, and
``Ruleset.apply_move`` refuses PLAY decisions with ``NotImplementedError``
rather than reporting a transition that did not happen.
"""

from shed.engine.events import (
    ArrangementCommitted,
    BurnReason,
    CardRevealed,
    CardsDrawn,
    CardsPlayed,
    Decision,
    GameEnded,
    GameStarted,
    HandDealt,
    ObservedEvent,
    PileBurned,
    PilePickedUp,
    Transition,
    UndoRecord,
    filter_event_for,
    filter_events_for,
)
from shed.engine.rules import (
    OPENING_RANK_ORDER,
    Ruleset,
    can_play_rank,
    legal_moves,
    select_opening_player,
)
from shed.engine.state import (
    GameState,
    Outcome,
    PlayerState,
    PlayerView,
    PublicPlayerState,
    SetupState,
    build_view,
    deal_initial_state,
    dealing_order,
    derive_active_zone,
    public_player_state,
    shuffled_deck,
    validate_decision_boundary,
)
from shed.engine.types import (
    DEFAULT_DEALER,
    DEFAULT_RULES,
    ORDINARY_RANKS,
    SUIT_ORDER,
    Arrange,
    AtLeast,
    AtMost,
    Card,
    CardId,
    IllegalMoveError,
    Move,
    Phase,
    PickUp,
    Play,
    PlayConstraint,
    PlayerId,
    Rank,
    Reveal,
    RulesConfig,
    SlotId,
    StateInvariantError,
    Suit,
    Unrestricted,
    Zone,
    build_deck,
)

__all__ = [
    "DEFAULT_DEALER",
    "DEFAULT_RULES",
    "OPENING_RANK_ORDER",
    "ORDINARY_RANKS",
    "SUIT_ORDER",
    "Arrange",
    "ArrangementCommitted",
    "AtLeast",
    "AtMost",
    "BurnReason",
    "Card",
    "CardId",
    "CardRevealed",
    "CardsDrawn",
    "CardsPlayed",
    "Decision",
    "GameEnded",
    "GameStarted",
    "GameState",
    "HandDealt",
    "IllegalMoveError",
    "Move",
    "ObservedEvent",
    "Outcome",
    "Phase",
    "PickUp",
    "PileBurned",
    "PilePickedUp",
    "Play",
    "PlayConstraint",
    "PlayerId",
    "PlayerState",
    "PlayerView",
    "PublicPlayerState",
    "Rank",
    "Reveal",
    "RulesConfig",
    "Ruleset",
    "SetupState",
    "SlotId",
    "StateInvariantError",
    "Suit",
    "Transition",
    "UndoRecord",
    "Unrestricted",
    "Zone",
    "build_deck",
    "build_view",
    "can_play_rank",
    "deal_initial_state",
    "dealing_order",
    "derive_active_zone",
    "filter_event_for",
    "filter_events_for",
    "legal_moves",
    "public_player_state",
    "select_opening_player",
    "shuffled_deck",
    "validate_decision_boundary",
]
